apiVersion: v1
data:
  client.key.pem: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUZkZzNMSWhkblozbTZhU0ZqT3d2YW1vNFI1TGc2RHFpZGZDSkh4MnNtRGxvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFWXFMTGY3TG5YS1dVRmp3bmltRitKNk1pYkp6R3Q5bVJsbHVBUzJmNTJmMG12Ui9odlBOaQpEaEhxZ0UwRUJZaiswci9ONTQ3UjM5Mllxd3U5UHNFZ3FBPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
kind: Secret
metadata:
  creationTimestamp: null
  name: signing-key
  namespace: trust-anchor
