---
# Source: gx-registry/templates/deployment-registry.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gx-registry
  namespace: infra
  labels:
    app.kubernetes.io/name: gx-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gx-registry
  template:
    metadata:
      annotations:
        randstring: "AZtvXjSD"
      labels:
        app.kubernetes.io/name: gx-registry
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
        - name: wait-for-kubo
          image: busybox
          command:
            - sh
            - -c
            - until nc -z gx-registry-kubo 5001; do echo waiting for Kubo; sleep 2; done;
        - name: local-trust
          image: quay.io/wi_stefan/gaiax-local-trust:0.0.1
          imagePullPolicy: Always
          env:
            - name: ROOT_CA
              value: "MIIFnDCCA4SgAwIBAgIBATANBgkqhkiG9w0BAQsFADBnMQswCQYDVQQGEwJERTEPMA0GA1UECAwGU2F4b255MRAwDgYDVQQHDAdEcmVzZGVuMRMwEQYDVQQKDApGSUNPREVTIENBMRMwEQYDVQQDDApGSUNPREVTLUNBMQswCQYDVQQFEwIwMTAeFw0yNTA1MDgxMjQ2MDVaFw0zNTA1MDYxMjQ2MDVaMGcxCzAJBgNVBAYTAkRFMQ8wDQYDVQQIDAZTYXhvbnkxEDAOBgNVBAcMB0RyZXNkZW4xEzARBgNVBAoMCkZJQ09ERVMgQ0ExEzARBgNVBAMMCkZJQ09ERVMtQ0ExCzAJBgNVBAUTAjAxMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAv1H4FWaE8eIN975w6PGQ+LjkuyOXh56vR7Ufz/d1TbzQpr4jfAZQIsf1FsFHdnwOuwSvd42m6UZsdmBkaaMRLAy/Lc305+bMwHottgYmPhJwTQXmiqyngPvG7+F7GubYpwoe4jta2h8XsrAzD8iy5DA4tI3lGdK0qoV8WrIA+IW7yy5l/bCVomPTAYH/07Ae4IyfA7tTXUOSy/ON47q3cwPeHMVfR79hBLLRIdaqf6924ulGB0RbAOMCaDaXZBrr+GLWvq038tiNW9O183ffLMQcetwcSe/PVQunb/ttSdlfRLX2SwMD9z/l6OPrBsSXdyPudv0eWTGgWP1Guj7quiW5qsjYJK+uivbh+9GeIYJb8FRZsY1l5Co6xDMVVpV9jKHYiktk/01WFIcZU2t6U1i/QL25wqONEJDY2ppcZ1VGSUZwrGUUbKp+WvQmHc3Yi3YqCmxrtL6OTSW446MmyfuSlZ7BUsg9pOSi7/PDHzxY8qcgdSGZWrB+DqG1FuFIKteE2TpfHhzObwv9ej174jwZAwU/5Z8F6xCqH4dztqEbkmrWrGHlT0hzjCazDYM+3uQG8kFAZjbmMkXAeCNDefVeH8lZuwkRIPs39fw/0XQwcPP5qEn717uPXp3UOieHwj9Zy9F3csRR03pz9U8lkfCjjSwtFH1WF/4bXPZlRdcCAwEAAaNTMFEwHQYDVR0OBBYEFOjiwE9JHxxb2l/dblGPZB7FtU/XMB8GA1UdIwQYMBaAFOjiwE9JHxxb2l/dblGPZB7FtU/XMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggIBAEnnFafQQHF4OsI/q0hmAEYUSCnuGa/kuMpKJKIpb1unTKZ+7sJwA3sN9btngM7+EuhMRVhCa2iXhoGq+7WqwOaDS8xT52jEnWl0TI8UF3dKDHsJ7sEH03sTyTYybx0YfQpDd9R4ZGKbfycrNdrnwotguH75dnpQZ46Q/3JXOL3NLfjiIKbreyZJiP2K56bjQ1cNqLI5oNL3Rb2/LxBnRud2Jjuzrcb7FZ+rQbKROgEzXBwlt63VgoiiBdWpUKord+wqpMETnRSTWlbJE52lsQHgAyL7q0I5Xb/Ecr1d66AH7KR3vBttjc8NdxHsVTddt1Kw4doebgC3j0dOnYd4OXEBNH9f5hkQXdQ6o3SZdHCwKDRoEktKBFTCvTdkLweu28EDh9iSuD0RKiKXvCtX19NO39cksJEJecsduW1sodh28+SzNOCfzkS2/8iu94lHclJdjJpzpaMqYR2Sqwn3AUW33hIXZV7gT7MfLmZqVP9D+4pdEJzJXACOX7dhVjJcCruakHCC32zhufLrHPxSVJ1ukATjFjaok6HRyfgG6bvo9cAw5Mc2aBWkSsEW3q0anWqgUt2ZVezakP9OaqCh7MBOJdRNfkEwZ7oAN6bpokxbiVxyPRgkc3sd3pcU/yncxP0RXZaB/EAfdiipbRuVMZvDTXrZzeR59QUP6j+ijPRp"
          volumeMounts:
            - name: trust-anchor
              mountPath: /out
      containers:
        - name: gx-registry
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
          image: "registry.gitlab.com/gaia-x/lab/compliance/gx-registry:v2.8.1"
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "3000"
            - name: BASE_URI
              value: "https://registry.127.0.0.1.nip.io/v2"
            - name: BASE_URL
              value: "https://registry.127.0.0.1.nip.io/v2"
            - name: APP_PATH
              value: "/v2"
            - name: evsslonly
              value: "false"
            - name: revocationListURL
              value:
            - name: trustedIssuersURL
              value:
            - name: KUBO_HOST
              value: gx-registry-kubo
            - name: APP_BRANCH
              value: "main"
            - name: ONTOLOGY_VERSION
              value: "development"
            - name: PRIVATE_KEY_ALGORITHM
              value: "PS256"
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: "0"
              #- name: HTTPS_PROXY
              #  value: "http://squid-proxy.infra.svc.cluster.local:8888"
              #- name: HTTP_PROXY
              #  value: "http://squid-proxy.infra.svc.cluster.local:8888"
          envFrom:
            - secretRef:
                name: gx-registry-keypair
          volumeMounts:
            - name: registry-ipfs-data
              mountPath: /data/ipfs
            - name: trust-anchor
              mountPath: /data/ipfs/registry/
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            periodSeconds: 15
            initialDelaySeconds: 15
            failureThreshold: 10
            successThreshold: 1
            httpGet:
              path: /v2
              port: 3000
          readinessProbe:
            periodSeconds: 15
            initialDelaySeconds: 15
            failureThreshold: 10
            successThreshold: 1
            httpGet:
              path: /v2
              port: 3000
          resources: {}
      volumes:
        - name: trust-anchor
          emptyDir: {}
        - name: registry-ipfs-data
          emptyDir: {}
